//Auth
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR_SUCCESS = "SIGNIN_ERROR_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

//Movies
export const GET_MOVIES_REQUEST = "GET_MOVIES_REQUEST";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIE_REQUEST = "GET_MOVIE_REQUEST";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";

//Favorites
export const GET_FAVORITES_REQUEST = "GET_FAVORITES_REQUEST";
export const GET_FAVORITES_SUCCESS = "GET_FAVORITES_SUCCESS";
export const ADD_FAVORITES_REQUEST = "ADD_FAVORITES_REQUEST";
export const ADD_FAVORITES_SUCCESS = "ADD_FAVORITES_SUCCESS";
export const REMOVE_FAVORITES_REQUEST = "REMOVE_FAVORITES_REQUEST";
export const REMOVE_FAVORITES_SUCCESS = "REMOVE_FAVORITES_SUCCESS";

//Comments
export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";

//Rating
export const ADD_RATING_REQUEST = "ADD_RATING_REQUEST";
export const ADD_RATING_SUCCESS = "ADD_RATING_SUCCESS";